# Generated by Django 6.0.3 on 2026-03-19 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('especificacao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data_operacao', models.DateField()),
                ('produtoID', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
                ('responsavelID', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
